miLista = [1024,3,True,6.5]
miLista.append(False)
print(miLista)
miLista.insert(2,4.5)
print(miLista)
print(miLista.pop())
print(miLista)
print(miLista.pop(1))
print(miLista)
miLista.pop(2)
print(miLista)
print(miLista.sort())
print(miLista)
miLista.reverse()
print(miLista)
print(miLista.count(6.5))
print(miLista.index(4.5))
miLista.remove(6.5)
print(miLista)
del miLista[0]
print(miLista)

